### ISSUE TITLE
update minimum Hugo version

### ISSUE THREAD

**Issue by apreshill** [yihui/hugo-prose#12]
Hi @yihui,

I tried to build/deploy the site via Netlify using the current minimum version `0.54.0` and ran into build errors:
https://github.com/yihui/hugo-prose/blob/master/theme.toml#L8

Here is my log:
https://app.netlify.com/sites/sharp-colden-263590/deploys/5fae99f929769000f09eba3b

I upgraded to my local Hugo version `0.71.1` and it worked, but not sure if there is anything in between that would work :)

**Comment by apreshill** [comment]
Also I just noticed that you are using `0.78.0` to build on Netlify right now 😄

**Comment by yihui** [comment]
I meant to figure out the min version a few days ago but forgot it. It should be 0.55.0. Thank you!
