### ISSUE TITLE
Consider using Hugo mainSections?

### ISSUE THREAD

**Issue by apreshill** [yihui/hugo-prose#16]
Looking at the home page layout, wanted to see if you had considered using mainSections?

https://gohugo.io/functions/where/#mainsections

https://github.com/gohugoio/hugo/issues/3206

That way, folks could define in the config file which types of content shows up on the home page (i.e., cards may or may not be included, one could only include posts, etc).

**Comment by yihui** [comment]
Great idea! Done now. Thanks!
