### ISSUE TITLE
Chroma vs. highlight.js for syntax highlighting

### ISSUE THREAD

**Issue by sosiristseng** [yihui/hugo-prose#30]
By default, Hugo uses [Chroma](https://gohugo.io/content-management/syntax-highlighting/) for server-side rendering. 

Using Chroma brings us some benefits aligning with this theme's purpose:

- Superior client-side performance
- Elimination of an external JS dependency

with some potential drawbacks:

- Fewer color styles (however one could [customize the CSS](https://gohugo.io/content-management/syntax-highlighting/#generate-syntax-highlighter-css))
- Fewer [supported languages](https://gohugo.io/content-management/syntax-highlighting/#list-of-chroma-highlighting-languages)
- May break the habits of bookdown (Not quite sure about this because I only skimmed bookdown's docs)

Though I am aware of the parameter `disable_highlight`, which can turn off `highlight.js`, I would like to hear your opinion(s) about this.

**Comment by apreshill** [comment]
See also: https://ropensci.org/technotes/2020/04/30/code-highlighting/

**Comment by sosiristseng** [comment]
> Chroma works on Markdown content, so if you use blogdown to generate pages as html, you can only use client-side highlighting

(Edited) I also saw this: https://yihui.org/en/2017/07/on-syntax-highlighting/

I see, thanks for the material.
