### ISSUE TITLE
Enable scroll_highlight in TOC

### ISSUE THREAD

**Issue by apreshill** [yihui/hugo-prose#37]
Similar to `bookdown::gitbook` TOC

> The scroll_highlight option in toc indicates whether to enable highlighting of TOC items as you scroll the book body (by default this feature is enabled). Whenever a new header comes into the current viewport as you scroll down/up, the corresponding item in TOC on the left will be highlighted.

See also:
https://discourse.gohugo.io/t/hugo-themes-with-dynamic-toc-highlighting/10281/4
http://tscanlin.github.io/tocbot/

**Comment by gaospecial** [comment]
I also need this feature.

**Comment by yihui** [comment]
I just wrote some JS code to do it: https://github.com/yihui/misc.js/blob/main/js/toc-highlight.js The code is relatively simple (using Intersection Observers), and doesn't do fancy things such as collapsing other sections in the TOC. It only adds a class `active` to the current TOC item, and the default styling is to make it bold. You can further improve the JS, or tweak the style.
