### ISSUE TITLE
Generation of repository name twice in URL

### ISSUE THREAD

**Issue by haaforever** [yihui/hugo-prose#38]
Hello,
I'm trying to start my blog using hugo-prose with github page.
So I made "blog" repository in my github, and edit "config.yaml" as follows.

* baseurl: "https://haaforever.github.io/blog/"
* publishDir: "docs"

Here is a problem.
If I click other tabs (Home, About, Sitemap) , they don't work and show "404 page not found" message.
Here are their local addresses.

* http://127.0.0.1:4321/blog/blog/
* http://127.0.0.1:4321/blog/blog/about/
* http://127.0.0.1:4321/blog/blog/sitemap/

Could you help me with this problem?

**Comment by sosiristseng** [comment]
Set `canonifyURLs=true` in `config.toml`?

**Comment by haaforever** [comment]
Thank you, I solve it!
