### ISSUE TITLE
Bug: hovering footnote <sup> also pulls all footnote after it within same <p>

### ISSUE THREAD

**Issue by loikein** [yihui/hugo-prose#43]
Bug in action: (This is a general Markdown test document on vanilla Hugo server. I also tweaked the style a little bit to make the hovering more obvious. Not tested for Rmd or Blogdown.)

<img width="1054" alt="image" src="https://github.com/yihui/hugo-prose/assets/20618587/bb2bdf6f-0137-4186-8220-29206e854aa2">

I was able to find the exact CSS code that has caused this bug:

<img width="461" alt="image" src="https://github.com/yihui/hugo-prose/assets/20618587/3aa3cdb1-e3e5-473e-81b4-22bf5db6846e">

After changing from `~` to `+` in the selector, the hovering effect is now only pulling the intended footnote:

<img width="1038" alt="image" src="https://github.com/yihui/hugo-prose/assets/20618587/530786ea-631c-49e5-8476-5dc2cbba352a">

However, this CSS file seems to have been imported by some JS within this theme, and I am not very well-versed with JS. So, I am writing this issue to see if you would like to address it somehow. If there is another repo where you know the bug is coming from, please tell me and I can create an issue there as well.

Thank you very much for this beautiful theme as always.

**Comment by loikein** [comment]
I think I was able to find the source of this CSS code in one of your other repos:
https://github.com/yihui/misc.js/blob/main/css/article.css#L85
Would you like to fix it? I can make a PR over there as well if you want.

**Comment by yihui** [comment]
> changing from `~` to `+` in the selector

That's the right fix, which I just applied. Thank you very much!
