### ISSUE TITLE
Links don't get underlined in `_index.md`

### ISSUE THREAD

**Issue by lucharo** [yihui/hugo-prose#49]
Hey, 

Just started tinkering with `hugo-prose` today. I appreciate the minimalism of this theme and the fact that it's a WIP but I actually really like that, so that I can learn and make it my own.

Setting up my `_index.md` I noticed that the URLs don't get highlighted, which does happen in posts, see below:

<img width="1417" alt="image" src="https://github.com/yihui/hugo-prose/assets/47890755/ab331f13-a7d6-4a53-a9ff-1b23d6d4cd47">

I was wondering if this is by design/choice and how to change it/fix it, rather than manually underlining the links

**Comment by lucharo** [comment]
Found the culprit...

https://github.com/yihui/hugo-prose/blob/5b24f88f8e51180020844042e279c7519e0c8e14/static/css/style.css#L145-L148

Changed text-decoration to `underlined`

**Comment by yihui** [comment]
Or remove that line, since `underlined` is the default.
