### ISSUE TITLE
[QUESTION] Adding "description" to list.html

### ISSUE THREAD

**Issue by lucharo** [yihui/hugo-prose#51]
Hey @yihui, first of all, thanks so much for this theme, I am having a lot of fun and learning a lot making it my own

I am trying to add a description of sorts under "Posts" (as an example):
<img width="397" alt="image" src="https://github.com/yihui/hugo-prose/assets/47890755/c3c483dd-1856-4798-9289-f13ae3a249f6">

I see that the Posts or Work pages (from the example page) get rendered from the `list.html` template but I have not been able to figure out how parameters like `.IsHome` or `.Title` get passed down to the renderer. In essence, I would like to have a Posts page and a Work page with a short paragraph within them. When I create an `_index.md` in the `posts/` folder for example a "card" gets created instead of the plain HTML default output. See below: 

default page: 
![image](https://github.com/yihui/hugo-prose/assets/47890755/a82c1272-efff-4bca-b4b3-283d0f6444d6)

When I add `_index.md`: 

![image](https://github.com/yihui/hugo-prose/assets/47890755/cdd19387-bc99-4b54-a0e0-bb2f9a700255)

I'd like to keep the look of the default Posts page

**Comment by yihui** [comment]
> When I create an `_index.md` in the `posts/` folder for example a "card" gets created instead of the plain HTML default output.

The content of `_index.md` is rendered here:

https://github.com/yihui/hugo-prose/blob/63481f54dd3c4195816fad48438c0f33f7f29169/layouts/_default/list.html#L9-L13

You can use any HTML tags and style them with CSS as you wish.

**Comment by lucharo** [comment]
Thanks for pointing me to those lines, so if I change the `article-list` CSS I should be able to change the default behaviour of creating a card?

**Comment by yihui** [comment]
If I understand correctly, you want the style of the description to be different with cards. Then what you can do is use a different class name for the description and define the CSS for that class as necessary.

**Comment by lucharo** [comment]
Ok understood! Thanks :) I'll keep digging
