### ISSUE TITLE
Enable a GitHub Edit button or link to a page's source md/Rmd

### ISSUE THREAD

**Issue by apreshill** [yihui/hugo-prose#8]
As we detailed here in the book: https://bookdown.org/yihui/blogdown/templates.html#how-to

- Similar to the bookdown feature in the gitbook and bs4_book output formats. 

- Also one of the features we were unable to add in Distill (see: https://github.com/rstudio/distill/issues/163). 

- See it in action in the right sidebar on <https://ropensci.org/blog/2020/10/13/covidpreprints/>.

- Also similar to a nice feature of the [Airbnb knowledge repo](https://github.com/airbnb/knowledge-repo):

![airbnb](https://user-images.githubusercontent.com/12160301/98815418-19199a00-23f5-11eb-90a0-c12e068400b5.png)

**Comment by yihui** [comment]
Actually it has been enabled, but it might be too subtle to find. There is a "Suggest changes" section in the appendix, e.g., https://prose.yihui.org/about/ (scroll to the bottom, between "Reuse" and "Citation")

Personally I prefer a menu item, but people who are not familiar with Github may not understand what this feature means, so some explanation may help (which is what the text in "Suggest changes" does). I'll see what I can do.

**Comment by apreshill** [comment]
I see it now! Sorry I was just so used to the distill footer that I assumed it was the same and skimmed over the actual link in the text there :)

**Comment by yihui** [comment]
No worries.

It is also a menu item in the bottom menu now. The "Suggest changes" section in the appendix is still there.
